language: ruby
rvm:
- 2.2.0
sudo: false
before_script:
  - git config user.name "Travis CI"
  - git config user.email "build@travis-ci.org"
script: bundle exec rake deploy
env:
  global:
    secure: S+5O7TXrNLmtIIQuwktQwx9kAkf1FpC0FB4Uhrq2nsan2ToBlj49VQzaOUmw3HxQeNvlpD5k5EfLOwxKocwc4x38e7U2F+X133VWrmD7M5JyYaYSpBlzeoipiAG9RBnscAqmq5JLt9njUj6plgs9Qd0Q2Kz7pa630eavC7KDP6+pT2RAZVrUkreN3fEYij8fAmH9sAYHwmtN3o2uWvln3ctL2mK+ovR2LWqqDn+vzLkydlAqwR2v5+rwWcDDXCociEVUxuO9IUA7jPGDW5yX8PXxJJOucF/FGExM045RbZrCwx3meJrQQK71KHqoxKVjijCdIy4K+JvD8hNx5mOdt/fl9qDw1gXCrVsFZIOkmZZgjMpKecuheZtNmf7ayaeYtTLWvrIGmng/l/+GCWv/bpMMBRrGDMDFI4R02Kwgt+KZiZMNmsd93FVerWkGlvz3Zq1I7ef0u3PyYQtJ7pbz4+b/axUr1huTiGNcLngbf0+ra7bJFCfds1UZ2oDopZbcaZqbo+ZZ3jVGhm1VmZs9PEs07c3dQzNdAEWPM9dGPp+RNhyQeTnpcwunYLF+Du4+OtMSnJ9wpgwqQHfZiFKGjn31K4ys0GHzXtMFxpE64BZVNev7zvIA7RcOtZTdI04RDo2FZD+ySfpa0fjR0Krtqdw8rQT6wKiFIcc7nbGRRH8=
branches:
  only:
  - master
